"""Static reference table of F1 circuit lengths sourced from Wikipedia.

Keys match the FastF1 session.event["Location"] field (case-insensitive).
Generated by scripts/scrape_circuit_lengths.py on 2026-03-12, with manual
aliases added where FastF1 Location names differ from Wikipedia's location
column.

Source: https://en.wikipedia.org/wiki/List_of_Formula_One_circuits
"""

from __future__ import annotations

# Maps lowercase location names to circuit length in kilometres.
# For sessions with telemetry (2018+), the telemetry-derived value is used
# instead — this table is the tier-2 fallback for pre-2018 seasons.
CIRCUIT_LENGTHS_KM: dict[str, float] = {
    # --- Scraped from Wikipedia ---
    "abu dhabi": 5.281,
    "adelaide": 3.78,
    "aintree": 4.828,
    "anderstorp": 4.031,
    "austin": 5.513,
    "baku": 6.003,
    "berlin": 8.3,
    "bern": 7.208,
    "bowmanville": 3.957,
    "buenos aires": 4.259,
    "casablanca": 7.618,
    "castle donington": 4.02,
    "dallas": 3.901,
    "detroit": 4.023,
    "east london": 3.92,
    "estoril": 4.36,
    "greater noida": 5.141,
    "gueux": 8.302,
    "heusden-zolder": 4.262,
    "hockenheim": 4.574,
    "imola": 4.909,
    "istanbul": 5.338,
    "jeddah": 6.174,
    "jerez de la frontera": 4.428,
    "le castellet": 5.842,
    "le mans": 4.43,
    "lisbon": 5.44,
    "long beach": 3.275,
    "lusail": 5.419,
    "magny-cours": 4.411,
    "marina bay": 4.94,
    "melbourne": 5.278,
    "mexico city": 4.304,
    "miami gardens": 5.412,
    "midrand": 4.261,
    "mimasaka": 3.703,
    "mogyoród": 4.381,
    "mont-tremblant": 4.265,
    "monte carlo": 3.337,
    "montmeló": 4.657,
    "montreal": 4.361,
    "monza": 5.793,
    "moreno valley": 5.271,
    "nivelles": 3.724,
    "nürburg": 5.148,
    "orival": 6.542,
    "oyama": 4.563,
    "paradise": 6.201,
    "phoenix": 3.72,
    "portimão": 4.653,
    "porto": 7.775,
    "prenois": 3.886,
    "rio de janeiro": 5.031,
    "sakhir": 5.412,
    "san sebastián de los reyes": 3.314,
    "scarperia e san piero": 5.245,
    "sebring": 8.356,
    "sepang": 5.543,
    "shanghai": 5.451,
    "silverstone": 5.891,
    "sochi": 5.848,
    "speedway": 4.192,
    "spielberg": 4.318,
    "stavelot": 7.004,
    "suzuka": 5.807,
    "são paulo": 4.309,
    "valencia": 5.419,
    "watkins glen": 5.43,
    "west kingsdown": 4.206,
    "yeongam": 5.615,
    "zandvoort": 4.259,
    "zeltweg": 3.186,
    # --- FastF1 Location aliases ---
    # FastF1 uses "Sakhir" for the city; some older sessions may use "Bahrain"
    "bahrain": 5.412,
    # FastF1 uses "Barcelona" for Circuit de Catalunya (Montmeló); the scraped
    # "barcelona" entry (6.316) is the 1951 Pedralbes circuit — override it.
    "barcelona": 4.657,
    # FastF1 uses "Budapest" instead of the municipality "Mogyoród"
    "budapest": 4.381,
    # Las Vegas circuit is technically in "Paradise, NV" — FastF1 uses "Las Vegas"
    "las vegas": 6.201,
    # FastF1 uses "Miami" rather than "Miami Gardens"
    "miami": 5.412,
    # Mugello hosted the 2020 Tuscan GP; FastF1 uses "Mugello" not "Scarperia e San Piero"
    "mugello": 5.245,
    # FastF1 uses "Spa" or "Spa-Francorchamps" rather than the municipality "Stavelot"
    "spa": 7.004,
    "spa-francorchamps": 7.004,
}


def lookup_circuit_length_km(location: str) -> float | None:
    """Look up circuit length from the static Wikipedia-sourced table.

    Performs case-insensitive exact match first, then falls back to an
    unambiguous substring match.

    Args:
        location: Circuit location string (e.g. session.event["Location"])

    Returns:
        Circuit length in km, or None if not found or ambiguous
    """
    if not location:
        return None
    key = location.lower().strip()

    # Tier 1: exact match
    if key in CIRCUIT_LENGTHS_KM:
        return CIRCUIT_LENGTHS_KM[key]

    # Tier 2: unambiguous substring match (query must be a substring of a dict key)
    matches = [(k, v) for k, v in CIRCUIT_LENGTHS_KM.items() if key in k]
    if len(matches) == 1:
        return matches[0][1]

    return None
